<?php

/**
 * @file
 * Contains iso2019_global.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function iso2019_global_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the iso2019_global module.
    case 'help.page.iso2019_global':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_page().
 */
function iso2019_global_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'iso2019_global/iso2019';
}
